version: "3.8"

services:
# БД postgres
  shortener-test-postgres:
    container_name: shortener-test-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: praktikum
    expose:
      - "5432"
    networks:
      test:
        ipv4_address: 192.168.160.11

# go
  shortener-test-golang:
    container_name: shortener-test-golang
    build:
      context: go
    volumes:
      - .:/app
      - ./autotests/shortenertestbeta:/usr/local/bin/shortenertestbeta
      - ./autotests/random:/usr/local/bin/random
    depends_on:
      - shortener-test-postgres
    networks:
      test:
        ipv4_address: 192.168.160.10

networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.160.0/24
